### 1.Write down a numpy program to repeat the elements of an array

### 2.Illustrate two dimensional array with an example

### 3.Input a two  2 dimensional arrays.give options for the user such as addition of both the arrays, concatenation of arrays, difference of both arrays product of the arrays
### 4.Write a numpy program to create a 3 cross 3 identity matrix if at all we take wrong input give the input from user

### 5. Write a NumPy program to create a new shape to an array without changing its data. 

### 6. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.

### 7. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.

### 8. Write a NumPy program to make an array immutable (read-only)

In [4]:
import numpy as np

In [5]:
#(1)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[1 1 2 2 3 3 4 4]


In [7]:
#(2)
array = np.array([[1,2],[3,4]])
print(array)

[[1 2]
 [3 4]]


In [12]:
#(3)
array1 = np.array(list(map(int,input('Enter frst matrix : ').split())))
array2 = np.array(list(map(int,input('Enter second matrix : ').split())))
array1 = np.resize(array1,(2,2))
array2 = np.resize(array2,(2,2))
print(array1+array2)

Enter frst matrix : 1 2 3 4
Enter second matrix : 5 6 7 8
[[ 6  8]
 [10 12]]


In [13]:
#(4)
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#(5)
array1 = np.array([[1,2,3],[4,5,6]])
array1 = np.resize(array1,(3,2))
print(array1)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
#(6)
print(np.array(list(range(0,51))))
print(np.array(list(range(10,51))))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [17]:
#(7)
x = np.zeros((2, 3, 4))
print(x)
print('first array',np.moveaxis(x, 0, -1).shape)
print('second array',np.moveaxis(x, -1, 0).shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
first array (3, 4, 2)
second array (4, 2, 3)


In [18]:
#(8)
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only